[package]
name = "arbtree"
version = "0.1.2"
authors = ["ilmari-h"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ilmari-h/arbtree.rs"
description = "A small library for general purpose tree data structures"

[dependencies]
